### ISSUE TITLE
great work! any chance to support fp16 inference?

### ISSUE THREAD

**Issue by FlotingDream** [XiangZ-0/HiT-SR#1]
great work! any chance to support fp16 inference? thx!

**Comment by XiangZ-0** [comment]
Hi, thanks for your interest. Our work is mainly built on [BasicSR](https://github.com/XPixelGroup/BasicSR). Unfortunately, it seems that BasicSR doesn't support fp16 at the moment (https://github.com/XPixelGroup/BasicSR/issues/477#issuecomment-934294844).

**Comment by FlotingDream** [comment]
> Hi, thanks for your interest. Our work is mainly built on [BasicSR](https://github.com/XPixelGroup/BasicSR). Unfortunately, it seems that BasicSR doesn't support fp16 at the moment ([XPixelGroup/BasicSR#477 (comment)](https://github.com/XPixelGroup/BasicSR/issues/477#issuecomment-934294844)).

I mean for HiT-srf (I only test this), use the pretrain model inference in fp16 will get black image. seems maybe some improve in the scc class select position bias part? thx

**Comment by FlotingDream** [comment]
Thanks for the quick reply, it was very helpful, appreciated!
